name: ulearn_riverpod
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  build_runner: ^2.4.9
  flutter:
    sdk: flutter
  riverpod_generator: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_riverpod: ^2.5.1
  dots_indicator: ^3.0.0
  fluttertoast: ^8.2.6
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/voice/
